### 异常体系
```
Throwable <--- Error
            \_ Exception <--- RuntimeException
```

- Error: 表示程序无法处理的严重错误，可能会导致程序终止，比如`OutOfMemoryError StackOverflowError NoClassDefFoundError`
- Exception: 继承这个类的异常(除了`RuntimeException`)称为**编译时异常/受检异常**，比如`IOException FileNotFoundException`
- RuntimeException: 继承这个类的异常称为**运行时异常/非受检异常**，比如`NullPointerException`

### 使用异常
在`Java`中，与异常相关的关键字有`try catch finally throw throws`。

- try：用来标记需要监控异常的代码
- catch：捕获代码捕获的异常并进行处理
- finally：兜底
- throw：抛出异常
- throws：声明函数抛出的异常

使用模式入下
```
try {
    //监控的代码
} catch (/*抛出的异常*/) {
    //异常处理逻辑
} finally {
    //兜底操作
}
```

### 异常处理
当监控的代码抛出异常，被捕获到时，一般有3种处理方式

1. 记录日志，内部消化

```
public void f() throws IOException {...}

public void g() {
    try {
        f();
    } catch (IOException e) {
        log.warn("...", e)
    }
}
```

2. 原封不动再抛出

```
public void f() throws IOException {...}

public void g() throws IOException {
    f();
}
```

3. 包装成新异常再抛出

```
public class NewException extends Exception {...}

public void f() throws IOException {...}

public void g() throws NewException {
    try {
        f();
    } catch (IOException e) {
        throw new NewException("...", e);
    }
}
```

#### 如何选择使用哪种异常处理方式
原则：函数只抛出调用方可识别（知道如何处理）的异常。

- 如果异常不影响业务，可以内部消化，记录日志即可
- 如果异常影响业务，业务可识别，那么可以原封不动地抛出
- 否则，包装成业务方可识别的异常再抛出

#### 注意事项
如果是包装异常的话，记得通过构造函数将原异常的cause传入新异常，这样**异常调用链**才不会断开。

### 异常调用链
异常调用链记录了引起异常的整个过程，跟函数调用一样，会追溯到引起异常调用链的最原始的异常，并记录了每个异常的生命周期。

```
public class ExceptionLifecycle {

    public static class LowException extends Exception {
        public LowException(String msg) {
            super(msg);
        }
    }

    public static class MidException extends Exception {
        public MidException(String msg, Throwable cause) {
            super(msg, cause);
        }
    }

    public static class HighException extends RuntimeException {
        public HighException(String msg, Throwable cause) {
            super(msg, cause);
        }
    }

    public static void fa() throws LowException {
        throw new LowException("low-exception-msg");
    }

    public static void fb() throws MidException {
        try {
            fa();
        } catch (LowException e) {
            throw new MidException("mid-exception-msg", e);
        }
    }

    public static void fc() {
        try {
            fb();
        } catch (MidException e) {
            throw new HighException("high-exception-msg", e);
        }
    }

    public static void main(String[] args) {
        fc();
    }
}
```
输出如下，每个异常只打印自己的生命周期
```
Exception in thread "main" top.hombio.ExceptionLifecycle$HighException: high-exception-msg
	at top.hombio.ExceptionLifecycle.fc(ExceptionLifecycle.java:39)
	at top.hombio.ExceptionLifecycle.main(ExceptionLifecycle.java:47)
Caused by: top.hombio.ExceptionLifecycle$MidException: mid-exception-msg
	at top.hombio.ExceptionLifecycle.fb(ExceptionLifecycle.java:31)
	at top.hombio.ExceptionLifecycle.fc(ExceptionLifecycle.java:37)
	... 1 more
Caused by: top.hombio.ExceptionLifecycle$LowException: low-exception-msg
	at top.hombio.ExceptionLifecycle.fa(ExceptionLifecycle.java:24)
	at top.hombio.ExceptionLifecycle.fb(ExceptionLifecycle.java:29)
	... 2 more
```
其中 `1 more` 表示省略输出了一个异常栈，如下。`2 more`类似，目的是为了减少重复输出。
```
at top.hombio.ExceptionLifecycle.main(ExceptionLifecycle.java:47)
```